<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 10.2 - Deployment via Flask

### Introduction

**Note**: This notebook should work on your local machine.

The purpose of this lab is to take you through the process of deploying a machine learning web app on a publicly hosted platform (Render). A trained model will be created using the Scikit-learn pipeline (combining loading, preprocessing and training steps), then separate files of Python code and text will need to be completed to make deployment possible. Firstly the app will be deployed to your local machine (so that you can view it in your browser). Once that it is successful, the files will be uploaded to a new repository you create in GitHub and then Render will read from this to host the application via a publicly accessible URL. 

The app will take in a text string from a user and output a prediction of whether that string is expressing positive or negative sentiment. The model is created using methods from Module 8 (Natural Language Processing). Since the training data used to create the model is small (300 records), the prediction may only be accurate around 70% of the time. In future you may wish to improve this app's performance or develop your own app in a similar manner.

The following files are needed to create the app:

- requirements.txt
- app.py
- Procfile
- model.joblib
- utils.py
- templates/ (folder containing index.html)
- static/ (folder containing css/style.css)


Firstly we will see how a predictive model can be created as a pipe which combines the preprocessing, feature engineering and model training steps. This model is then saved as a joblib pickle file which can be reloaded at any time to avoid retraining.

This trained model can be loaded within your production environment along with required packages and real-time predictions can be made by calling its predict() method. 

Flask is a web app framework written in Python. It enables one to run application code whose output can be viewed on a browser. It is installed as a Python library via `pip install flask`. For a sample "Hello World" application see https://palletsprojects.com/p/flask/.

Note that Flask does not scale up for use in large deployment applications (ones involving many frequent API requests).

### Model Training and Testing

In [2]:
## Import Libraries
import numpy as np
import pandas as pd
import regex as re
import spacy
import joblib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.base import BaseEstimator, TransformerMixin

The training data set is `sentiments.csv`, a dataset used in the NLP module.

In [2]:
# Read in the data
df = pd.read_csv('sentiments.csv')

In [3]:
df.head()

text  sentiment source
0                           Wow... Loved this place.          1   yelp
1                                 Crust is not good.          0   yelp
2          Not tasty and the texture was just nasty.          0   yelp
3  Stopped by during the late May bank holiday of...          1   yelp
4  The selection on the menu was great and so wer...          1   yelp

Next we define a function to do some preprocessing.

In [4]:
def clean_text(text):
    # reduce multiple spaces and newlines to only one
    text = re.sub(r'(\s\s+|\n\n+)', r'\1', text)
    # remove double quotes
    text = re.sub(r'"', '', text)

    return text

In [5]:
df['text'] = df['text'].apply(clean_text)

The following NLP model is used for further preprocessing. The following steps are the same as used in Module 8.

In [5]:
# import and load trained English model for spaCy
import en_core_web_sm
nlp = en_core_web_sm.load()

In [7]:
def convert_text(text):
    sent = nlp(text)
    ents = {x.text: x for x in sent.ents}
    tokens = []
    for w in sent:
        if w.is_stop or w.is_punct:
            continue
        if w.text in ents:
            tokens.append(w.text)
        else:
            tokens.append(w.lemma_.lower())
    text = ' '.join(tokens)

    return text

In [8]:
df['short'] = df['text'].apply(convert_text)

In [9]:
df.head()

text  sentiment source  \
0                           Wow... Loved this place.          1   yelp   
1                                 Crust is not good.          0   yelp   
2          Not tasty and the texture was just nasty.          0   yelp   
3  Stopped by during the late May bank holiday of...          1   yelp   
4  The selection on the menu was great and so wer...          1   yelp   

                                               short  
0                                     wow love place  
1                                         crust good  
2                                tasty texture nasty  
3  stop late bank holiday rick steve recommendati...  
4                         selection menu great price

In [10]:
# Features and Labels
X = df['short']
y = df['sentiment']

In [11]:
# split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 101)

In [12]:
X_train

1488    particularly remember sense assault strident c...
683                          good food great atmosphere.1
1199                                      film way long  
579                     service fan quick serve nice folk
2877                                            excellent
                              ...                        
599                                            good money
1599    line WRITTEN year old try oh hard sound like y...
1361    interesting action suspense unneeded controver...
1547    terribly disappointed film receive award accol...
863                                         love fry bean
Name: short, Length: 2400, dtype: object

In [13]:
classifier = LinearSVC()

In [14]:
# create a matrix of word counts from the text
# use TF-IDF
tfidf = TfidfVectorizer()
# do the actual counting
A = tfidf.fit_transform(X_train)

# train the classifier with the training data
classifier.fit(A, y_train)

# do the transformation for the test data
# NOTE: use `transform()` instead of `fit_transform()`
B = tfidf.transform(X_test)

# make predictions based on the test data
predictions = classifier.predict(B)

# check the accuracy
print('Accuracy: %.4f' % accuracy_score(y_test, predictions))

Accuracy: 0.7733


In [15]:
A

<2400x3643 sparse matrix of type '<class 'numpy.float64'>'
	with 12362 stored elements in Compressed Sparse Row format>

In [16]:
A.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

We will not attempt to improve on the performance in this lab as we are more interested in how to deploy the model.

Next we create a pipeline to simplify the process of model creation. We first define a preprocessor class which applies the `clean_text` and `convert_text` functions defined earlier.

In [17]:
class preprocessor(TransformerMixin, BaseEstimator):

    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self

    def transform(self, X):
         return X.apply(clean_text).apply(convert_text)

Next we combine the preprocessing, feature engineering and modelling steps into a single pipe.

In [18]:
pipe = make_pipeline(preprocessor(), TfidfVectorizer(), LinearSVC())
pipe.fit(df['text'],df['sentiment'])

Pipeline(steps=[('preprocessor', preprocessor()),
                ('tfidfvectorizer', TfidfVectorizer()),
                ('linearsvc', LinearSVC())])

In [25]:
pipe = make_pipeline(preprocessor(), tfidf, classifier)
pipe.fit(df['text'],df['sentiment'])

Pipeline(steps=[('preprocessor', preprocessor()),
                ('tfidfvectorizer', TfidfVectorizer()),
                ('linearsvc', LinearSVC())])

**Exercise**: test the resulting model on phrases of positive and negative sentiment.

In [20]:
pipe.predict(pd.Series('awesome'))

array([1], dtype=int64)

In [21]:
pipe.predict(pd.Series('like'))

array([1], dtype=int64)

In [22]:
pipe.predict(pd.Series('hate'))

array([0], dtype=int64)

In [23]:
pipe.predict(pd.Series('awful'))

array([0], dtype=int64)

In [33]:
pd.Series('awful')

0    awful
dtype: object

Once satisified that we have a model ready for deployment, we can write a self-contained script that creates the model and saves it as a joblib file. By doing so from a script rather than the notebook we simplify the process when deploying.

**Exercise**: Review the code in model.py and run "python model.py" via an Anaconda prompt (Windows) or Terminal window (Mac). This creates a file model.joblib.

Let us load this model and verify that it alone can be used to make predictions.

In [24]:
newpipe = joblib.load(open('model.joblib','rb'))

In [25]:
type(newpipe)

sklearn.pipeline.Pipeline

Testing this out:

In [26]:
print(newpipe.predict(pd.Series('awesome place'))[0])
print(newpipe.predict(pd.Series('terrible!'))[0])
print(newpipe.predict(pd.Series('very interesting'))[0])

1
0
1


In [31]:
newpipe.predict(pd.Series('awesome place'))

array([1], dtype=int64)

In [32]:
newpipe.predict(pd.Series('awesome place'))[0]

1

We can then write a self-contained script that loads the model and can make predictions on the fly. This is partially done for you in the file "app.py".

**Exercise**: Refer to app.py and fill in the missing code based on the code above using a text editor such as Spyder. Observe how it links to utils.py which contains the preprocessing functions.

### Local hosting

**Exercise**: Open the index.html with the text editor and fill in the missing HTML code there.

Using Anaconda prompt (Windows) or a Terminal window (Mac) run "python app.py". This deploys the app locally on http://127.0.0.1:5000/ (or similar) which you can then view on the browser.

Feel free to be creative and redesign the webpage by modifying the .css and .html pages.

**Bonus Exercise**: Redesign the webpage by modifying the .css and .html pages.

### Deployment via Render

So far you have deployed your model on your local machine. Now we seek to deploy it publicly.

There are two additional files needed for external deployment of your model: 
- requirements.txt includes the versions of packages that are to be used with the app. 
- Procfile specifies the processes to be run on the virtualised Linux containers used to run web apps. 

In the Procfile you will see mention of `gunicorn`. Gunicorn (Green Unicorn) manages the Flask application. It is a Python HTTP server for applications over a Web Service Gateway Interface (WSGI). It allows one to run a Python application concurrently by running multiple processes on a single machine. Further information is at https://docs.gunicorn.org/en/stable/.

To update the `requirements.txt` file (**recommended!**) use the `__version__` attribute to see the version of packages being used or check via conda prompt. This ensures that your model is reproducible on other computing environments.

In [3]:
joblib.__version__

'1.1.1'

In [6]:
en_core_web_sm.__version__

'3.3.0'

In [10]:
re.__version__

'2.5.123'

In [11]:
pd.__version__

'1.4.4'

In [12]:
np.__version__

'1.23.3'

Log into your GitHub account (create one if you have not already done so) and create a new repository containing the following files.

- requirements.txt
- app.py
- Procfile
- model.joblib
- utils.py
- templates/ (folder containing index.html)
- static/ (folder containing css/style.css)

Next sign up for a free account at https://dashboard.render.com/register (a Platform As A Service) by connecting via your GitHub account.

Once signed into dashboard.render.com click "New Web Service" under Web Services.

From "connect GitHub account", select the repository containing the above files.

Choose a unique name for the web service and leave the root directory blank. Under "start command" enter "gunicorn app:app"

Finally click "Create Web Service". It may take a few minutes to work but 
upon seeing "Booting worker with pid:" go to the url specified. An example can be seen at https://sentiment-app.onrender.com

**If the deployment fails, adjust the Python version by clicking on the "Environment" tab and entering two environment variables for Key `PYTHON_VERSION` and Value `3.9.13`**


If you managed to see your app successfully, congratulations! You now know how to deploy an app on the cloud.

Note that if working in part of a larger software system it is good practice to have versioning of code (e.g. with GitHub) and also make use of CI/CD software.

### References

More information on pipelines:
- https://gist.github.com/amberjrivera/8c5c145516f5a2e894681e16a8095b5c
- https://scikit-learn.org/stable/modules/compose.html#pipeline

More on Flask for web app deployment:
- https://flask.palletsprojects.com/en/1.1.x/quickstart/

Deploying Flask apps on Render:
- https://render.com/docs/deploy-flask



---



---



> > > > > > > > > © 2023 Institute of Data


---



---



